src/Entity/Stock.php
<?php

declare(strict_types=1);

/*
 * This file is part of vins
 *
 * (c) Aurelien Morvan <morvan.aurelien@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Admin\Traits\ValueListTrait;
use App\Entity\Interfaces\UpdatableInterface;
use App\Entity\Traits\TimeStampableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Stock
 *
 * @ORM\Table(name="amo_stock")
 * @ORM\Entity(repositoryClass="App\Repository\StockRepository")
 */
class Stock extends AbstractEntity implements UpdatableInterface
{
    use TimeStampableTrait;
    use ValueListTrait;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    protected $quantity = 0;

    /**
     * @var StockEntry[]|Collection
     *
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\StockEntry", mappedBy="stock", cascade={"persist", "remove"}, orphanRemoval=true
     *     )
     */
    protected $stockEntries;

    /**
     * @var Capacity
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Capacity", inversedBy="stock", cascade={"remove"}, orphanRemoval=true)
     * @ORM\JoinColumn(name="amo_capacity_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $capacity;

    protected $wine;

    public function __construct()
    {
        $this->stockEntries = new ArrayCollection();
        parent::__construct();
    }

    public function setQuantity(int $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * @return int
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    public function updateQuantityAfterOrder(int $quantity)
    {
        $this->quantity += $quantity;
    }

    public function __toString()
    {
        return sprintf(
            '%s - %s - %s',
            $this->capacity->getWine(),
            $this->capacity->getType(),
            $this->capacity->getQuantity()
        );
    }

    /**
     * @return StockEntry[]|Collection
     */
    public function getStockEntries()
    {
        return $this->stockEntries;
    }

    public function addStockEntry(StockEntry $entry)
    {
        $this->stockEntries->add($entry);
        $entry->setStock($this);

        return $this;
    }

    public function updateQuantity(
        StockEntry $entry,
        string $type
    ): void {
        switch ($type) {
            case 'add':
                $this->quantity += $entry->getQuantity();
                break;
            case 'remove':
                if ($entry->getTypeEntry() === StockEntry::TYPE_IN) {
                    $this->quantity -= $entry->getQuantity();
                } else {
                    $this->quantity += $entry->getQuantity();
                }
                break;
        }
    }

    public function removeStockEntry(StockEntry $entry)
    {
        $this->updateQuantity(
            $entry,
            'remove'
        );
        $this->stockEntries->removeElement($entry);
    }

    public function getDomain(): WineDomain
    {
        return $this->capacity->getWine()->getDomain();
    }

    /**
     * @return Capacity
     */
    public function getCapacity(): Capacity
    {
        return $this->capacity;
    }

    /**
     * @param Capacity $capacity
     */
    public function setCapacity(Capacity $capacity): void
    {
        $this->capacity = $capacity;
    }

    public function updateStockAfterUpdate(int $value, string $type)
    {
        switch ($type) {
            case StockEntry::TYPE_IN:
                $this->quantity += $value;
                break;
            case StockEntry::TYPE_OUT:
                $this->quantity -= $value;
                break;
        }
    }

    public function countTotalBottlesSold()
    {
        $cpt = 0;

        foreach ($this->stockEntries as $stockEntry) {
            if ($stockEntry->getTypeEntry() === StockEntry::TYPE_OUT && $stockEntry->getOrder() instanceof Order) {
                $cpt += $stockEntry->getQuantity();
            }
        }

        return $cpt;
    }

    public function getWine()
    {
        return $this->capacity->getWine();
    }
}

templates/cart/add_item_product.html.twig
<div class="modal-content add-product-modal">
    <div class="modal-header text-center">
        <div class="d-flex w-100">
            <div class="container-fluid">
                <div class="row">

                    <div class="col-2">
                        <img src="{{ vich_uploader_asset(dto.wine, 'imageFile') }}" height="100px"/>
                    </div>
                    <div class="col-10">
                        <div class="card-wine_content-product_content d-flex flex-column justify-content-around align-items-center">
                            <span class="font-weight-bold" style="color: {{ dto.wine.profile.color }}">{{ dto.wine.vintageName }}</span>
                            <span>{{ dto.wine.year }}</span>
                            <span>{{ dto.wine.domain }}</span>
                            <span>{{ dto.wine.appellation }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% form_theme form 'forms/_layout.html.twig' %}
        {{ form_start(form, {'attr': {'class': 'addWineCart'}, 'action': path('add_wine_to_card', {'id': dto.wine.id})}) }}
        <table class="table table-responsive product-table mb-0">
            <tbody>

            {% for element in form.elements %}
            <tr>
                <td>
                    <div>
                        <span>{{ element.vars.data.capacity.type }} {{ element.vars.data.capacity.quantity }}L</span>
                    </div>
                </td>
                <td>{{ element.vars.data.capacity|applyPromo }}€</td>
                <td></td>
                <td>
                    <div class="md-form mb-0 mt-0">
                        {{ form_widget(element.quantity) }}
                    </div>
                </td>
            </tr>
                {% if form_errors(element.quantity) %}
                    <tr>
                        <td colspan="4" class="text-left">
                            {{ form_errors(element.quantity) }}
                        </td>
                    </tr>
                {% endif %}
        {% endfor %}
        </tbody>
        </table>
        <div class="d-flex justify-content-end">
            <button class="button-custom btn-floating d-flex justify-content-center align-items-center">
                <i class="fas fa-shopping-cart"></i>
            </button>
        </div>
        {{ form_end(form) }}
    </div>
</div>

templates/cart/payment_button.html.twig
{% if payment_possible %}
<div id="container-payment" class="row">
    <div class="col-12">
        <form action="" method="POST" class="texf-center">
            <script
                    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="{{stripe_public_key }}"
                    data-amount="{{ cart.getTotalPriceWithDelivery() * 100 }}"
                    data-name="Mon Premier Sommelier"
                    data-currency="eur"
                    data-label="Procéder au paiement"
                    data-email="{{ cart.deliveryInformation.email}}"
                    data-image="{{asset('build/images/logo.png')}}"
                    data-locale="fr"
                    data-zip-code="false">
            </script>
            <button type="submit" class="btn btn-sm btn-outline-success btn-rounded waves-effect float-right">Procéder au paiement</button>
        </form>
    </div>
</div>
{% endif %}